"""by_mrpmv_01

Revision ID: 3365bd362ef7
Revises: 
Create Date: 2023-04-15 17:35:57.006519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3365bd362ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crd_user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_crd_user_id'), 'crd_user', ['id'], unique=False)
    op.create_table('ext_boton_consume_error',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ext_boton_consume_error_id'), 'ext_boton_consume_error', ['id'], unique=False)
    op.create_index(op.f('ix_ext_boton_consume_error_queue'), 'ext_boton_consume_error', ['queue'], unique=False)
    op.create_index(op.f('ix_ext_boton_consume_error_status'), 'ext_boton_consume_error', ['status'], unique=False)
    op.create_table('ext_boton_deposit',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('confirmation', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.String(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('system_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fnc_bank_payment',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_payment_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('input_unique_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('wage', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bank_payment_id'], ['fnc_bank_payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fnc_bank_payment_id'), 'fnc_bank_payment', ['id'], unique=False)
    op.create_table('fnc_bank_profile',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_no', sa.String(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('card_no', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'is_default', name='just_one_default_account')
    )
    op.create_index(op.f('ix_fnc_bank_profile_id'), 'fnc_bank_profile', ['id'], unique=False)
    op.create_index('merchant_default_account', 'fnc_bank_profile', ['merchant_id', 'is_default'], unique=False)
    op.create_table('fnc_bank_transactions',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fnc_bank_transactions_id'), 'fnc_bank_transactions', ['id'], unique=False)
    op.create_table('fnc_commission',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('pgw_commission_constant', sa.Integer(), nullable=False),
    sa.Column('pgw_commission_rate', sa.Float(), nullable=False),
    sa.Column('pgw_fee_constant', sa.Integer(), nullable=True),
    sa.Column('pgw_fee_rate', sa.Float(), nullable=True),
    sa.Column('credit_commission_constant', sa.Integer(), nullable=False),
    sa.Column('credit_commission_rate', sa.Float(), nullable=False),
    sa.Column('credit_limit', sa.Integer(), nullable=False),
    sa.Column('decrease_fee_on_pay_gw_settle', sa.Boolean(), nullable=True),
    sa.Column('decrease_commission_on_refund', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fnc_commission.merchant_v_category', 'fnc_commission', ['merchant_id', 'category'], unique=False)
    op.create_index(op.f('ix_fnc_commission_id'), 'fnc_commission', ['id'], unique=False)
    op.create_table('fnc_debt_user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('input_type', sa.String(), nullable=True),
    sa.Column('input_unique_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fnc_debt_user_id'), 'fnc_debt_user', ['id'], unique=False)
    op.create_index(op.f('ix_fnc_debt_user_user_id'), 'fnc_debt_user', ['user_id'], unique=False)
    op.create_table('ntf_provider',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('line_number', sa.String(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_number')
    )
    op.create_index(op.f('ix_ntf_provider_id'), 'ntf_provider', ['id'], unique=False)
    op.create_table('ntf_template',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ntf_template_id'), 'ntf_template', ['id'], unique=False)
    op.create_table('ord_pay',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('merchant_order_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('merchant_user_id', sa.String(), nullable=False),
    sa.Column('merchant_redirect_url', sa.String(), nullable=False),
    sa.Column('settle_id', sa.Integer(), nullable=True),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_order_id', 'merchant_id', name='merchant_order')
    )
    op.create_index(op.f('ix_ord_pay_id'), 'ord_pay', ['id'], unique=False)
    op.create_index(op.f('ix_ord_pay_merchant_user_id'), 'ord_pay', ['merchant_user_id'], unique=False)
    op.create_table('so_coin',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('fa_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('wallex_symbol', sa.String(), nullable=True),
    sa.Column('ltv', sa.Float(), nullable=True),
    sa.Column('price_in_rial', sa.Float(), nullable=True),
    sa.Column('price_in_usdt', sa.Float(), nullable=True),
    sa.Column('logo_address', sa.String(length=1024), nullable=True),
    sa.Column('networks', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_so_coin_id'), 'so_coin', ['id'], unique=False)
    op.create_table('so_merchant',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_fa', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('logo_address', sa.String(length=1024), nullable=True),
    sa.Column('logo_background_color', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_fa')
    )
    op.create_index(op.f('ix_so_merchant_id'), 'so_merchant', ['id'], unique=False)
    op.create_index(op.f('ix_so_merchant_name'), 'so_merchant', ['name'], unique=True)
    op.create_table('so_rule',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('rules', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_so_rule_id'), 'so_rule', ['id'], unique=False)
    op.create_table('uas_crypto_transaction',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('input_unique_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uas_crypto_transaction_id'), 'uas_crypto_transaction', ['id'], unique=False)
    op.create_table('uas_fiat_transaction',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('input_unique_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uas_fiat_transaction_id'), 'uas_fiat_transaction', ['id'], unique=False)
    op.create_table('uas_wallet_address',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('national_code', sa.String(), nullable=False),
    sa.Column('coin_name', sa.String(), nullable=False),
    sa.Column('network_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('national_code', 'coin_name', 'network_name', 'memo', name='uas_wallet_address_unique')
    )
    op.create_index(op.f('ix_uas_wallet_address_id'), 'uas_wallet_address', ['id'], unique=False)
    op.create_index('uas_wallet_address_index', 'uas_wallet_address', ['national_code', 'coin_name', 'network_name'], unique=False)
    op.create_table('uas_wallex_transaction',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('input_unique_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uas_wallex_transaction_id'), 'uas_wallex_transaction', ['id'], unique=False)
    op.create_table('usr_group',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fa_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_usr_group_id'), 'usr_group', ['id'], unique=False)
    op.create_table('usr_kyc',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sabte_ahval_inquired_at', sa.DateTime(), nullable=True),
    sa.Column('sabte_ahval_track_no', sa.String(), nullable=True),
    sa.Column('sabte_ahval_verified', sa.Boolean(), nullable=True),
    sa.Column('shahkar_inquired_at', sa.DateTime(), nullable=True),
    sa.Column('shahkar_verified', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usr_kyc_id'), 'usr_kyc', ['id'], unique=False)
    op.create_table('usr_otp_sent',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usr_otp_sent_mobile'), 'usr_otp_sent', ['mobile'], unique=False)
    op.create_table('usr_scope',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('fa_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_usr_scope_id'), 'usr_scope', ['id'], unique=False)
    op.create_table('usr_session',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('browser_version', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('token_first_used_at', sa.DateTime(), nullable=True),
    sa.Column('token_last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', 'user_id', name='usr_session_unique')
    )
    op.create_index(op.f('ix_usr_session_id'), 'usr_session', ['id'], unique=False)
    op.create_index(op.f('ix_usr_session_token'), 'usr_session', ['token'], unique=False)
    op.create_index(op.f('ix_usr_session_user_id'), 'usr_session', ['user_id'], unique=False)
    op.create_table('wlx_login',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_uuid', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('wallex_login_url', sa.String(length=1024), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expire_in', sa.String(), nullable=True),
    sa.Column('wallex_user_id', sa.String(), nullable=True),
    sa.Column('kyc_level', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallpay_error', sa.String(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wlx_login_code'), 'wlx_login', ['code'], unique=False)
    op.create_index(op.f('ix_wlx_login_state'), 'wlx_login', ['state'], unique=False)
    op.create_table('wlx_pay_in',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('input_unique_id', sa.Integer(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('redirect_url', sa.String(), nullable=True),
    sa.Column('callback_url', sa.String(), nullable=True),
    sa.Column('wallex_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wlx_pay_in_token'), 'wlx_pay_in', ['token'], unique=False)
    op.create_index(op.f('ix_wlx_pay_in_uuid'), 'wlx_pay_in', ['uuid'], unique=False)
    op.create_table('crd_calculator',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=True),
    sa.Column('input_unique_id', sa.Integer(), nullable=True),
    sa.Column('non_free_credit', sa.BigInteger(), nullable=False),
    sa.Column('used_non_free_credit', sa.BigInteger(), nullable=False),
    sa.Column('free_credit', sa.Integer(), nullable=False),
    sa.Column('used_free_credit', sa.Integer(), nullable=False),
    sa.Column('asset_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cs', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['crd_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crd_calculator_id'), 'crd_calculator', ['id'], unique=False)
    op.create_table('fnc_payment_gateway',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payment_gateway_id', sa.Integer(), nullable=True),
    sa.Column('bank_payment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('wage', sa.Integer(), nullable=True),
    sa.Column('gateway_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ref_num', sa.String(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('psp_purchase_id', sa.String(), nullable=True),
    sa.Column('psp_switching_url', sa.String(length=1024), nullable=True),
    sa.Column('callback_status', sa.String(), nullable=True),
    sa.Column('psp_status', sa.String(), nullable=True),
    sa.Column('psp_trace_no', sa.String(), nullable=True),
    sa.Column('payer_ip', sa.String(), nullable=True),
    sa.Column('psp_ref_num', sa.String(), nullable=True),
    sa.Column('psp_rrn', sa.String(), nullable=True),
    sa.Column('payer_masked_card_num', sa.String(), nullable=True),
    sa.Column('psp_name', sa.String(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reverse_status', sa.String(), nullable=True),
    sa.Column('refund_batch_id', sa.String(), nullable=True),
    sa.Column('refund_transfer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bank_payment_id'], ['fnc_bank_payment.id'], ),
    sa.ForeignKeyConstraint(['payment_gateway_id'], ['fnc_payment_gateway.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fnc_payment_gateway_id'), 'fnc_payment_gateway', ['id'], unique=False)
    op.create_index(op.f('ix_fnc_payment_gateway_ref_num'), 'fnc_payment_gateway', ['ref_num'], unique=False)
    op.create_table('fnc_transfer',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_profile_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('transfer_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bank_profile_id'], ['fnc_bank_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fnc_transfer_id'), 'fnc_transfer', ['id'], unique=False)
    op.create_index(op.f('ix_fnc_transfer_transfer_id'), 'fnc_transfer', ['transfer_id'], unique=False)
    op.create_table('ntf_notification_center',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=True),
    sa.Column('input_unique_id', sa.Integer(), nullable=True),
    sa.Column('with_push_notification', sa.Boolean(), nullable=True),
    sa.Column('with_sms', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['ntf_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ntf_notification_center_id'), 'ntf_notification_center', ['id'], unique=False)
    op.create_table('ntf_push_notification',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('input_unique_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('retrying_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('exception', sa.String(), nullable=True),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['ntf_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ntf_push_notification_id'), 'ntf_push_notification', ['id'], unique=False)
    op.create_table('ntf_sms',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(), nullable=False),
    sa.Column('input_unique_id', sa.Integer(), nullable=False),
    sa.Column('retrying_count', sa.Integer(), nullable=False),
    sa.Column('last_retried', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ntf_provider.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['ntf_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_type', 'input_unique_id')
    )
    op.create_index(op.f('ix_ntf_sms_id'), 'ntf_sms', ['id'], unique=False)
    op.create_table('ord_fund',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_free_credit', sa.Integer(), nullable=False),
    sa.Column('used_non_free_credit', sa.Integer(), nullable=False),
    sa.Column('repaid_free_credit', sa.Integer(), nullable=True),
    sa.Column('repaid_non_free_credit', sa.Integer(), nullable=True),
    sa.Column('used_asset_json', sa.JSON(), nullable=True),
    sa.Column('extra_money_to_pay', sa.Integer(), nullable=True),
    sa.Column('need_collateral', sa.Boolean(), nullable=True),
    sa.Column('collateral_confirmed', sa.Boolean(), nullable=True),
    sa.Column('need_wallex_asset', sa.Boolean(), nullable=True),
    sa.Column('wallex_block_request_id', sa.String(), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('completely_repaid_at', sa.DateTime(), nullable=True),
    sa.Column('fill_percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ord_pay.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_ord_fund_id'), 'ord_fund', ['id'], unique=False)
    op.create_table('uas_crypto_withdraw',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address_id', sa.Integer(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=True),
    sa.Column('from_memo', sa.String(), nullable=True),
    sa.Column('to_address', sa.String(), nullable=False),
    sa.Column('to_memo', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('ack', sa.Integer(), nullable=True),
    sa.Column('verify', sa.Integer(), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('is_identical', sa.Integer(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('tx_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_address_id'], ['uas_wallet_address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uas_crypto_withdraw_id'), 'uas_crypto_withdraw', ['id'], unique=False)
    op.create_index(op.f('ix_uas_crypto_withdraw_trace_id'), 'uas_crypto_withdraw', ['trace_id'], unique=False)
    op.create_table('usr_group_scopes',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['usr_group.id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['usr_scope.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'scope_id', name='group_scopes_unique')
    )
    op.create_index(op.f('ix_usr_group_scopes_id'), 'usr_group_scopes', ['id'], unique=False)
    op.create_table('usr_user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_pass', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('national_code', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('NOT(mobile IS NULL AND username IS NULL)'),
    sa.ForeignKeyConstraint(['kyc_id'], ['usr_kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usr_user_id'), 'usr_user', ['id'], unique=False)
    op.create_index(op.f('ix_usr_user_identifier'), 'usr_user', ['identifier'], unique=False)
    op.create_index(op.f('ix_usr_user_mobile'), 'usr_user', ['mobile'], unique=True)
    op.create_index(op.f('ix_usr_user_national_code'), 'usr_user', ['national_code'], unique=True)
    op.create_index(op.f('ix_usr_user_username'), 'usr_user', ['username'], unique=True)
    op.create_table('fnc_settle_credit',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_uuid', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_id'], ['fnc_transfer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'type', name='FncSettleCredit_fnc_order.id__type')
    )
    op.create_index('FncSettleCredit_fnc_order_id__type', 'fnc_settle_credit', ['order_id', 'type'], unique=False)
    op.create_index(op.f('ix_fnc_settle_credit_id'), 'fnc_settle_credit', ['id'], unique=False)
    op.create_index(op.f('ix_fnc_settle_credit_merchant_id'), 'fnc_settle_credit', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_fnc_settle_credit_order_id'), 'fnc_settle_credit', ['order_id'], unique=False)
    op.create_index(op.f('ix_fnc_settle_credit_order_uuid'), 'fnc_settle_credit', ['order_uuid'], unique=False)
    op.create_table('fnc_settle_pgw',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_uuid', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_id'], ['fnc_transfer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'type', name='FncSettlePgw_fnc_order.id__type')
    )
    op.create_index('FncSettlePgw_fnc_order_id__type', 'fnc_settle_pgw', ['order_id', 'type'], unique=False)
    op.create_index(op.f('ix_fnc_settle_pgw_id'), 'fnc_settle_pgw', ['id'], unique=False)
    op.create_index(op.f('ix_fnc_settle_pgw_merchant_id'), 'fnc_settle_pgw', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_fnc_settle_pgw_order_id'), 'fnc_settle_pgw', ['order_id'], unique=False)
    op.create_index(op.f('ix_fnc_settle_pgw_order_uuid'), 'fnc_settle_pgw', ['order_uuid'], unique=False)
    op.create_table('ord_debt',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('settlement_time', sa.DateTime(), nullable=False),
    sa.Column('payment_detail_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['ord_fund.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id')
    )
    op.create_index(op.f('ix_ord_debt_id'), 'ord_debt', ['id'], unique=False)
    op.create_table('ord_loan',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_position', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('settlement_time', sa.DateTime(), nullable=False),
    sa.Column('payment_detail_id', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['ord_fund.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ord_loan_id'), 'ord_loan', ['id'], unique=False)
    op.create_table('usr_user_groups',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['usr_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usr_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='user_groups_unique')
    )
    op.create_index(op.f('ix_usr_user_groups_id'), 'usr_user_groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usr_user_groups_id'), table_name='usr_user_groups')
    op.drop_table('usr_user_groups')
    op.drop_index(op.f('ix_ord_loan_id'), table_name='ord_loan')
    op.drop_table('ord_loan')
    op.drop_index(op.f('ix_ord_debt_id'), table_name='ord_debt')
    op.drop_table('ord_debt')
    op.drop_index(op.f('ix_fnc_settle_pgw_order_uuid'), table_name='fnc_settle_pgw')
    op.drop_index(op.f('ix_fnc_settle_pgw_order_id'), table_name='fnc_settle_pgw')
    op.drop_index(op.f('ix_fnc_settle_pgw_merchant_id'), table_name='fnc_settle_pgw')
    op.drop_index(op.f('ix_fnc_settle_pgw_id'), table_name='fnc_settle_pgw')
    op.drop_index('FncSettlePgw_fnc_order_id__type', table_name='fnc_settle_pgw')
    op.drop_table('fnc_settle_pgw')
    op.drop_index(op.f('ix_fnc_settle_credit_order_uuid'), table_name='fnc_settle_credit')
    op.drop_index(op.f('ix_fnc_settle_credit_order_id'), table_name='fnc_settle_credit')
    op.drop_index(op.f('ix_fnc_settle_credit_merchant_id'), table_name='fnc_settle_credit')
    op.drop_index(op.f('ix_fnc_settle_credit_id'), table_name='fnc_settle_credit')
    op.drop_index('FncSettleCredit_fnc_order_id__type', table_name='fnc_settle_credit')
    op.drop_table('fnc_settle_credit')
    op.drop_index(op.f('ix_usr_user_username'), table_name='usr_user')
    op.drop_index(op.f('ix_usr_user_national_code'), table_name='usr_user')
    op.drop_index(op.f('ix_usr_user_mobile'), table_name='usr_user')
    op.drop_index(op.f('ix_usr_user_identifier'), table_name='usr_user')
    op.drop_index(op.f('ix_usr_user_id'), table_name='usr_user')
    op.drop_table('usr_user')
    op.drop_index(op.f('ix_usr_group_scopes_id'), table_name='usr_group_scopes')
    op.drop_table('usr_group_scopes')
    op.drop_index(op.f('ix_uas_crypto_withdraw_trace_id'), table_name='uas_crypto_withdraw')
    op.drop_index(op.f('ix_uas_crypto_withdraw_id'), table_name='uas_crypto_withdraw')
    op.drop_table('uas_crypto_withdraw')
    op.drop_index(op.f('ix_ord_fund_id'), table_name='ord_fund')
    op.drop_table('ord_fund')
    op.drop_index(op.f('ix_ntf_sms_id'), table_name='ntf_sms')
    op.drop_table('ntf_sms')
    op.drop_index(op.f('ix_ntf_push_notification_id'), table_name='ntf_push_notification')
    op.drop_table('ntf_push_notification')
    op.drop_index(op.f('ix_ntf_notification_center_id'), table_name='ntf_notification_center')
    op.drop_table('ntf_notification_center')
    op.drop_index(op.f('ix_fnc_transfer_transfer_id'), table_name='fnc_transfer')
    op.drop_index(op.f('ix_fnc_transfer_id'), table_name='fnc_transfer')
    op.drop_table('fnc_transfer')
    op.drop_index(op.f('ix_fnc_payment_gateway_ref_num'), table_name='fnc_payment_gateway')
    op.drop_index(op.f('ix_fnc_payment_gateway_id'), table_name='fnc_payment_gateway')
    op.drop_table('fnc_payment_gateway')
    op.drop_index(op.f('ix_crd_calculator_id'), table_name='crd_calculator')
    op.drop_table('crd_calculator')
    op.drop_index(op.f('ix_wlx_pay_in_uuid'), table_name='wlx_pay_in')
    op.drop_index(op.f('ix_wlx_pay_in_token'), table_name='wlx_pay_in')
    op.drop_table('wlx_pay_in')
    op.drop_index(op.f('ix_wlx_login_state'), table_name='wlx_login')
    op.drop_index(op.f('ix_wlx_login_code'), table_name='wlx_login')
    op.drop_table('wlx_login')
    op.drop_index(op.f('ix_usr_session_user_id'), table_name='usr_session')
    op.drop_index(op.f('ix_usr_session_token'), table_name='usr_session')
    op.drop_index(op.f('ix_usr_session_id'), table_name='usr_session')
    op.drop_table('usr_session')
    op.drop_index(op.f('ix_usr_scope_id'), table_name='usr_scope')
    op.drop_table('usr_scope')
    op.drop_index(op.f('ix_usr_otp_sent_mobile'), table_name='usr_otp_sent')
    op.drop_table('usr_otp_sent')
    op.drop_index(op.f('ix_usr_kyc_id'), table_name='usr_kyc')
    op.drop_table('usr_kyc')
    op.drop_index(op.f('ix_usr_group_id'), table_name='usr_group')
    op.drop_table('usr_group')
    op.drop_index(op.f('ix_uas_wallex_transaction_id'), table_name='uas_wallex_transaction')
    op.drop_table('uas_wallex_transaction')
    op.drop_index('uas_wallet_address_index', table_name='uas_wallet_address')
    op.drop_index(op.f('ix_uas_wallet_address_id'), table_name='uas_wallet_address')
    op.drop_table('uas_wallet_address')
    op.drop_index(op.f('ix_uas_fiat_transaction_id'), table_name='uas_fiat_transaction')
    op.drop_table('uas_fiat_transaction')
    op.drop_index(op.f('ix_uas_crypto_transaction_id'), table_name='uas_crypto_transaction')
    op.drop_table('uas_crypto_transaction')
    op.drop_index(op.f('ix_so_rule_id'), table_name='so_rule')
    op.drop_table('so_rule')
    op.drop_index(op.f('ix_so_merchant_name'), table_name='so_merchant')
    op.drop_index(op.f('ix_so_merchant_id'), table_name='so_merchant')
    op.drop_table('so_merchant')
    op.drop_index(op.f('ix_so_coin_id'), table_name='so_coin')
    op.drop_table('so_coin')
    op.drop_index(op.f('ix_ord_pay_merchant_user_id'), table_name='ord_pay')
    op.drop_index(op.f('ix_ord_pay_id'), table_name='ord_pay')
    op.drop_table('ord_pay')
    op.drop_index(op.f('ix_ntf_template_id'), table_name='ntf_template')
    op.drop_table('ntf_template')
    op.drop_index(op.f('ix_ntf_provider_id'), table_name='ntf_provider')
    op.drop_table('ntf_provider')
    op.drop_index(op.f('ix_fnc_debt_user_user_id'), table_name='fnc_debt_user')
    op.drop_index(op.f('ix_fnc_debt_user_id'), table_name='fnc_debt_user')
    op.drop_table('fnc_debt_user')
    op.drop_index(op.f('ix_fnc_commission_id'), table_name='fnc_commission')
    op.drop_index('fnc_commission.merchant_v_category', table_name='fnc_commission')
    op.drop_table('fnc_commission')
    op.drop_index(op.f('ix_fnc_bank_transactions_id'), table_name='fnc_bank_transactions')
    op.drop_table('fnc_bank_transactions')
    op.drop_index('merchant_default_account', table_name='fnc_bank_profile')
    op.drop_index(op.f('ix_fnc_bank_profile_id'), table_name='fnc_bank_profile')
    op.drop_table('fnc_bank_profile')
    op.drop_index(op.f('ix_fnc_bank_payment_id'), table_name='fnc_bank_payment')
    op.drop_table('fnc_bank_payment')
    op.drop_table('ext_boton_deposit')
    op.drop_index(op.f('ix_ext_boton_consume_error_status'), table_name='ext_boton_consume_error')
    op.drop_index(op.f('ix_ext_boton_consume_error_queue'), table_name='ext_boton_consume_error')
    op.drop_index(op.f('ix_ext_boton_consume_error_id'), table_name='ext_boton_consume_error')
    op.drop_table('ext_boton_consume_error')
    op.drop_index(op.f('ix_crd_user_id'), table_name='crd_user')
    op.drop_table('crd_user')
    # ### end Alembic commands ###
