"""by_mrpmv_02

Revision ID: 4dbbfaf38ea5
Revises: 3365bd362ef7
Create Date: 2023-04-15 17:36:13.310186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbbfaf38ea5'
down_revision = '3365bd362ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fnc_bank_payment', sa.Column('success_pgw_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fnc_bank_payment', 'fnc_payment_gateway', ['success_pgw_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fnc_bank_payment', type_='foreignkey')
    op.drop_column('fnc_bank_payment', 'success_pgw_id')
    # ### end Alembic commands ###
