"""add foreignkey for commission_id to ord_pay_07

Revision ID: 702777b17373
Revises: 2b141640d9e9
Create Date: 2023-05-15 15:23:19.900929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702777b17373'
down_revision = '2b141640d9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fnc_transfer', 'merchant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'ord_pay', 'ord_commission', ['commission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ord_pay', type_='foreignkey')
    op.alter_column('fnc_transfer', 'merchant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
