"""by_mrpmv_05

Revision ID: adf8a4d56223
Revises: 1086441049bc
Create Date: 2023-05-03 20:47:37.718710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adf8a4d56223'
down_revision = '1086441049bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usr_merchant',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_fa', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('logo_address', sa.String(length=1024), nullable=True),
    sa.Column('logo_background_color', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_fa')
    )
    op.create_index(op.f('ix_usr_merchant_id'), 'usr_merchant', ['id'], unique=False)
    op.create_index(op.f('ix_usr_merchant_name'), 'usr_merchant', ['name'], unique=True)
    op.create_table('usr_user_merchants',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['usr_merchant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usr_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_id', name='user_merchant_unique')
    )
    op.create_index(op.f('ix_usr_user_merchants_id'), 'usr_user_merchants', ['id'], unique=False)
    op.drop_index('ix_so_merchant_id', table_name='so_merchant')
    op.drop_index('ix_so_merchant_name', table_name='so_merchant')
    op.drop_table('so_merchant')
    op.add_column('fnc_transfer', sa.Column('merchant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_fnc_transfer_merchant_id'), 'fnc_transfer', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fnc_transfer_merchant_id'), table_name='fnc_transfer')
    op.drop_column('fnc_transfer', 'merchant_id')
    op.create_table('so_merchant',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name_fa', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('logo_address', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('logo_background_color', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='so_merchant_pkey'),
    sa.UniqueConstraint('name_fa', name='so_merchant_name_fa_key')
    )
    op.create_index('ix_so_merchant_name', 'so_merchant', ['name'], unique=False)
    op.create_index('ix_so_merchant_id', 'so_merchant', ['id'], unique=False)
    op.drop_index(op.f('ix_usr_user_merchants_id'), table_name='usr_user_merchants')
    op.drop_table('usr_user_merchants')
    op.drop_index(op.f('ix_usr_merchant_name'), table_name='usr_merchant')
    op.drop_index(op.f('ix_usr_merchant_id'), table_name='usr_merchant')
    op.drop_table('usr_merchant')
    # ### end Alembic commands ###
